<body class="home page page-id-9 page-template page-template-t-page-php">
<?php include(VIEW_PATH.PLATFORM."/widgets/menu_mobile.phtml"); ?>
<div id="wrapper">
	<div id="header-bg"></div>
<div class="container">
<div class="row">
<?php include(VIEW_PATH.PLATFORM."/widgets/sidebar.phtml"); ?>
	<div id="main-content">
		<div id="inner-content">
				<h1 class="page-title"> Appetizers </h1>
				<hr class="headings">
				<div align="center">
				<div class="slider-wrapper theme-default">
					<div class="ribbon"></div>
					Taramosalata ............................................... $5 <br>
					Item 1 ............................................... $5 <br>
					Item 1 ............................................... $5 <br>
				</div>
		</div></div>
</div>