<!-- MOBILE MENU -->
<div id="top-bar"><div class="mobile-menu"><!--span-->
<form method="get" action="#/eatery/wp-content/themes/eatery/nav.php" >
 <div class="menu-main-menu-container"><select name="-Menu-"><option value="<?=$page_params['static_url']?>" id="menu-item-276" class="menu-item menu-item-type-post_type menu-item-object-page current-menu-item page_item page-item-9 current_page_item menu-item-276" selected="selected" >Home</option>
<option value="<?=$page_params['static_url']?>menu/dinner/" id="menu-item-383" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-383">Menu</option>
		<option value="<?=$page_params['static_url']?>menu/appetizers/" id="menu-item-799" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-799">&raquo;&raquo; Appetizers</option>
		<option value="<?=$page_params['static_url']?>menu/lunch/" id="menu-item-800" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-800">&raquo;&raquo; Lunch</option>
		<option value="<?=$page_params['static_url']?>menu/dinner/" id="menu-item-801" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-801">&raquo;&raquo; Dinner</option>
		<option value="<?=$page_params['static_url']?>menu/kids/" id="menu-item-801" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-801">&raquo;&raquo; Kids</option>
		<option value="<?=$page_params['static_url']?>menu/dessert/" id="menu-item-802" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-802">&raquo;&raquo; Dessert & Drinks</option>
		<option value="<?=$page_params['static_url']?>menu/specials/" id="menu-item-802" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-802">&raquo;&raquo; Specials</option>
		<option value="<?=$page_params['static_url']?>menu/group/" id="menu-item-802" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-802">&raquo;&raquo; Group</option>
<option value="<?=$page_params['static_url']?>reservations/" id="menu-item-196" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-196">Reservations</option>
<option value="<?=$page_params['static_url']?>contact/" id="menu-item-1070" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1070">Contact</option>
</select></div> <input class="mob-sub" type="submit" value="Go" />
</form>
<!--/span--></div></div>