<!-- BEGIN sidebar -->
<div id="sidebar-container" class="fourcol">
    <div id="sidebar">
        <div id="sidebarBorder">
            <div id="logo">
            <!-- <a href='/'><img src='images/logo1.png' alt='Caverne Logo' /></a> -->
            </div>
            <!-- ABOVE BEGIN--><div class='textCenter' ><div class="side-widget above"><div class="textwidget"><p>Clean, fresh greek food.</p>
</div></div><!--br class="clear"--></div><!-- ABOVE END-->

<div id="the-side-menu"><div class="menu-main-menu-container">
<ul id="sidebar-menu" class="sf-menu sf-vertical">
<li class="menu-item menu-item-type-post_type menu-item-object-page current-menu-item page_item page-item-9 current_page_item menu-item-276"><a href="<?=$page_params['static_url']?>">Home</a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-383"><a href="<?=$page_params['static_url']?>menu/dinner/">Services</a>
<ul class="sub-menu">
	<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-803"><a href="<?=$page_params['static_url']?>menu/appetizers/">Social Media</a></li>
	<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-833"><a href="<?=$page_params['static_url']?>menu/lunch/">Branding</a></li>
</li>
</ul>
</li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1070"><a href="<?=$page_params['static_url']?>contact/">Contact</a></li>
</ul></div><br class="clear" /></div>

<!--br class="clear"-->
<div class='textCenter' ><div class="side-widget below"><div class="textwidget"><p>Sun-Thu : 11am - 10pm<br />
Fri-Sat : 11am - 11pm</p>
<p style="font-style:italic">Bring your own wine</p>
</div></div><!--br class="clear"--></div><div class="side-widget below"><h2 class="sidebar-widget-title">Tel: 514-844-5114</h2>			<div class="textwidget"></div>
		</div><!--br class="clear"-->	<!-- BELOW END-->
            <!-- MOBILE BEGIN--><div class='textCenter' ><div class="side-widget mobile"><div class="textwidget"><p>Clean, crisp and designed to delight.</p>
</div></div></div>	<!-- MOBILE END-->
            <div class="side-widget below soc"><div class="textwidget"><a href="#" target="_blank" class="facebook"></a><a href="#" target="_blank" class="googleplus"></a></div><br class="clear" /></div>        </div>
    </div>
</div>
<!-- END sidebar -->    <div class="eightcol last">